package com.happix.sample

import com.happix.kexport.generated.Item
import com.happix.kexport.generated.User

fun main() {
    // These are type aliases generated by the kexport KSP processor.
    val user: User = User(id = 1, name = "Alice", email = "alice@example.com")
    val item: Item = Item(id = 42, name = "Widget", price = 9.99)

    println(user)
    println(item)
}
