package com.happix.kexport.processor

import com.google.devtools.ksp.processing.CodeGenerator
import com.google.devtools.ksp.processing.Dependencies
import com.google.devtools.ksp.processing.KSPLogger
import com.google.devtools.ksp.processing.Resolver
import com.google.devtools.ksp.processing.SymbolProcessor
import com.google.devtools.ksp.symbol.KSAnnotated
import com.google.devtools.ksp.symbol.KSClassDeclaration
import com.google.devtools.ksp.validate
import com.happix.kexport.annotation.Export

private const val ANNOTATION_NAME = "com.happix.kexport.annotation.Export"
private const val OUTPUT_PACKAGE = "com.happix.kexport.generated"
private const val OUTPUT_FILE = "Exports"

class ExportProcessor(
    private val codeGenerator: CodeGenerator,
    private val logger: KSPLogger,
    private val options: Map<String, String>,
) : SymbolProcessor {

    // Tracks whether we have already written the output file in a previous round.
    private var generated = false

    override fun process(resolver: Resolver): List<KSAnnotated> {
        val symbols = resolver.getSymbolsWithAnnotation(ANNOTATION_NAME)

        val (valid, deferred) = symbols.partition { it.validate() }

        val exports = resolveExports(valid)

        if (exports.isEmpty()) return deferred

        if (generated) {
            logger.warn("$OUTPUT_FILE already generated; skipping extra round.")
            return deferred
        }

        writeExportsFile(exports)

        generated = true

        return deferred
    }

    /**
     * Resolves the annotated classes and pairs each with its export name.
     * Returns a list of [ExportEntry]s for all valid annotated classes.
     */
    private fun resolveExports(
        validSymbols: List<KSAnnotated>,
    ): List<ExportEntry> {
        val allClasses = validSymbols.filterIsInstance<KSClassDeclaration>()

        val packageToScan = options["kexport.packageToScan"]
        val classes = if (packageToScan != null) {
            allClasses.filter { decl ->
                val pkg = decl.packageName.asString()
                pkg == packageToScan || pkg.startsWith("$packageToScan.")
            }
        } else {
            allClasses
        }

        return classes
            .sortedBy { it.simpleName.asString() }
            .mapNotNull { classDecl ->
                val qualifiedName = classDecl.qualifiedName?.asString()
                if (qualifiedName == null) {
                    logger.error("Cannot resolve qualified name for ${classDecl.simpleName.asString()}", classDecl)
                    return@mapNotNull null
                }
                ExportEntry(
                    classDeclaration = classDecl,
                    exportName = classDecl.determineExportName(),
                    qualifiedName = qualifiedName,
                )
            }
    }

    /**
     * Writes the generated file containing typealias declarations for all resolved exports.
     */
    private fun writeExportsFile(
        exports: List<ExportEntry>,
    ) {
        val packageToScan = options["kexport.packageToScan"]
        val outputPackage = options["kexport.outputPackage"] ?: packageToScan ?: OUTPUT_PACKAGE

        val sourceFiles = exports.mapNotNull { it.classDeclaration.containingFile }.toTypedArray()

        val outputStream = codeGenerator.createNewFile(
            dependencies = Dependencies(aggregating = true, *sourceFiles),
            packageName = outputPackage,
            fileName = OUTPUT_FILE,
        )

        outputStream.bufferedWriter().use { writer ->
            writer.appendLine("@file:Suppress(\"unused\")")
            writer.appendLine()
            writer.appendLine("package $outputPackage")
            writer.appendLine()
            writer.appendLine("// Auto-generated by kexport — do not edit manually.")
            writer.appendLine()

            for (entry in exports) {
                writer.appendLine("typealias ${entry.exportName} = ${entry.qualifiedName}")
            }
        }

        logger.info("Generated $outputPackage.$OUTPUT_FILE with ${exports.size} export(s).")
    }

    private fun KSClassDeclaration.determineExportName(): String {
        return this.annotations
            .firstOrNull { it.shortName.asString() == Export::class.simpleName }
            ?.arguments
            ?.firstOrNull { it.name?.asString() == "alias" }
            ?.value
            ?.toString()
            ?.takeIf { it.isNotBlank() }
            ?: this.simpleName.asString()
    }
}
